#!/usr/bin/env python3
"""Generate development inputs without modifying either immutable requirements bundle."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PRODUCTS = tuple(p for p in ("masonwing", "gleanbird") if (ROOT / f"{p}-requirements-v1.0.1").is_dir())


def encoded(value: object) -> bytes:
    return (json.dumps(value, ensure_ascii=False, indent=2) + "\n").encode()


def load(path: Path) -> object:
    return json.loads(path.read_text())


def generate() -> dict[Path, bytes]:
    outputs: dict[Path, bytes] = {}
    inventory = {"generated_by": "scripts/sync_specs.py", "spec_version": "1.0.1",
                 "wire_contract_version": "1.0.0", "products": {}, "input_files": []}
    all_cases, all_screens, contexts, command_paths = [], [], [], set()
    for product in PRODUCTS:
        base = ROOT / f"{product}-requirements-v1.0.1"
        namespace = f"{product.upper()}@1.0.1"
        for path in sorted(base.rglob("*")):
            if path.is_file() and "__pycache__" not in path.parts:
                inventory["input_files"].append({"path": str(path.relative_to(ROOT)),
                    "sha256": hashlib.sha256(path.read_bytes()).hexdigest()})
        catalog = load(base / "01-product/requirement-catalog.json")
        cases = load(base / "06-testing/test-cases.json")["cases"]
        screens = load(base / "05-ux/screens.json")["screens"]
        operations = load(base / "03-contracts/operations.json")["operations"]
        command_paths.update(path for path in load(base / "03-contracts/openapi.json")["paths"] if "/commands/" in path)
        packages = load(base / "07-delivery/work-packages.json")["packages"]
        suites = load(base / "06-testing/suites.json")["suites"]
        feature_by_id = {x["id"]: x for x in catalog["features"]}
        for case in cases:
            all_cases.append({"namespace": namespace, "product": product,
                "qualified_id": f"{namespace}:{case['id']}",
                "source": str((base / "06-testing/test-cases.json").relative_to(ROOT)), **case})
        for screen in screens:
            all_screens.append({"product": product, "qualified_id": f"{namespace}:{screen['id']}", **screen})
        for work in packages:
            feature = work.get("feature_id")
            if not feature or feature not in feature_by_id:
                continue
            screen = next((s for s in screens if s["feature_id"] == feature), None)
            contexts.append({"namespace": namespace, "product": product, "feature": feature_by_id[feature],
                "work_package": work, "screen": screen,
                "commands": [o for o in operations if o["feature_id"] == feature],
                "cases": [c["id"] for c in cases if c.get("feature_id") == feature],
                "implementation_status": "SCAFFOLD_NOT_ACCEPTED"})
        inventory["products"][product] = {
            "features": len(catalog["features"]), "requirements": len(catalog["requirements"]),
            "criteria": len(catalog["criteria"]), "quality_requirements": len(catalog["quality"]),
            "test_cases": len(cases), "suites": len(suites), "commands": len(operations),
            "screens": len(screens),
            "state_vectors": len(load(base / "06-testing/state-vectors.json")["vectors"]),
            "schema_definitions": len(load(base / "03-contracts/contracts.json")["$defs"])}
        for path in sorted((base / "03-contracts").rglob("*")):
            if path.is_file():
                outputs[ROOT / "contracts" / product / path.relative_to(base / "03-contracts")] = path.read_bytes()
        for path in sorted((base / "06-testing/features").glob("*.feature")):
            outputs[ROOT / "tests/acceptance/features" / product / path.name] = path.read_bytes()
    outputs[ROOT / "contracts/spec-inventory.json"] = encoded(inventory)
    outputs[ROOT / "contracts/domain-contexts.json"] = encoded({"contexts": contexts})
    outputs[ROOT / "tests/acceptance/catalog.json"] = encoded({"generated_by": "scripts/sync_specs.py", "cases": all_cases})
    outputs[ROOT / "packages/web-shell/src/generated/screens.json"] = encoded(all_screens)
    outputs[ROOT / "packages/web-shell/src/generated/summary.json"] = encoded(inventory["products"])
    outputs[ROOT / "packages/web-shell/src/generated/criteria.json"] = encoded([
        {key: case.get(key) for key in ("qualified_id", "product", "feature_id", "title", "preconditions", "steps", "expected", "suite_id")}
        for case in all_cases if case["kind"] == "acceptance"
    ])
    routes = "\n".join(f"    {json.dumps(path)}," for path in sorted(command_paths))
    outputs[ROOT / "crates/host-api/src/generated_routes.rs"] = (
        "// Generated by scripts/sync_specs.py from the local composition's OpenAPI inputs.\n"
        "// This catalog belongs to the executable composition, never the shared kernel/SDK.\n"
        "#[rustfmt::skip]\npub const LOCAL_COMMAND_PATHS: &[&str] = &[\n" + routes + "\n];\n"
    ).encode()
    feature_lines = ["# Feature → work package → tests", "",
        "Generated by `scripts/sync_specs.py`. Original namespaces, release phases and command names are preserved.", "",
        "| Namespace / feature | Name | Phase | Work package | Commands | Designed cases |",
        "| --- | --- | --- | --- | --- | ---: |"]
    for context in contexts:
        feature, work = context["feature"], context["work_package"]
        commands = ", ".join(f"`{operation['operation']}`" for operation in context["commands"]) or "Cross-cutting; no independent command"
        phase = work.get("phase") or feature.get("phase") or "See work package"
        name = feature.get("name", feature.get("title", feature["id"]))
        feature_lines.append(f"| `{context['namespace']}:{feature['id']}` | {name} | {phase} | `{work['id']}` | {commands} | {len(context['cases'])} |")
    feature_lines.extend(["", "All entries are scaffolded; case counts do not represent passed product acceptance.",
        "Full Given/When/Then: `tests/acceptance/catalog.json`. Dependency, owner and deliverable details: `contracts/domain-contexts.json`.", ""])
    outputs[ROOT / "docs/feature-map.md"] = "\n".join(feature_lines).encode()
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Reject missing files or any generated drift")
    args = parser.parse_args()
    outputs = generate()
    changed = []
    for path, content in outputs.items():
        if not path.exists() or path.read_bytes() != content:
            changed.append(str(path.relative_to(ROOT)))
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(content)
    if args.check and changed:
        print("Generated drift: " + ", ".join(changed))
        return 1
    print(f"{'Verified' if args.check else 'Generated'} {len(outputs)} files; {len(changed)} changed; baselines untouched")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
